# -*- coding: utf-8 -*-
"""SalaryData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ob_4LoINyFt5TEgk1Z-PIe2Ve6uskeXF
"""

#
#
#

import pandas as pd
import numpy as np
url="https://raw.githubusercontent.com/chrislockhartky/Data_1_Final/main/original_csv/MetroSalary.csv"
#Need to create a dataframe
df=pd.read_csv(url)
#Specific employee names are irrelevant and may lead to privacy concerns
#df.drop([columns='Employee_Name'], inplace=False, axis=1)
df=df[df.CalYear==2022]
df=df.drop(columns=["Employee_Name","Incentive_Allowance","Other","Annual_Rate"])
df.head()

